app = "polskifach-backend"
primary_region = "waw"

[build]

[env]
  DEBUG = "False"
  DJANGO_SETTINGS_MODULE = "core.settings"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  release_command = "python manage.py migrate"
